In [ ]:
pip install keras

In [ ]:
pip install ann_visualizer

In [ ]:
pip install graphviz

In [ ]:
pip install tensorflow

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Importing necessary models for implementation of ANN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense #, Activation,Layer,Lambda

In [3]:
forestfire=pd.read_csv('forestfires (2).csv')

In [4]:
forestfire.head()

month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  ...  monthfeb  \
0   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0  ...         0   
1   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0  ...         0   
2   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0  ...         0   
3   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2  ...         0   
4   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category  
0         0          small  
1         0          small  
2         0          small  
3         0          small  
4         0          small  

[5 rows x 31 columns]

In [5]:
forestfire.describe()

FFMC         DMC          DC         ISI        temp          RH  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean    90.644681  110.872340  547.940039    9.021663   18.889168   44.288201   
std      5.520111   64.046482  248.066192    4.559477    5.806625   16.317469   
min     18.700000    1.100000    7.900000    0.000000    2.200000   15.000000   
25%     90.200000   68.600000  437.700000    6.500000   15.500000   33.000000   
50%     91.600000  108.300000  664.200000    8.400000   19.300000   42.000000   
75%     92.900000  142.400000  713.900000   10.800000   22.800000   53.000000   
max     96.200000  291.300000  860.600000   56.100000   33.300000  100.000000   

             wind        rain         area      dayfri  ...    monthdec  \
count  517.000000  517.000000   517.000000  517.000000  ...  517.000000   
mean     4.017602    0.021663    12.847292    0.164410  ...    0.017408   
std      1.791653    0.295959    63.655818    0.371006  ...    0.130913   
min      0.400000    0.000000     0.000000    0.000000  ...    0.000000   
25%      2.700000    0.000000     0.000000    0.000000  ...    0.000000   
50%      4.000000    0.000000     0.520000    0.000000  ...    0.000000   
75%      4.900000    0.000000     6.570000    0.000000  ...    0.000000   
max      9.400000    6.400000  1090.840000    1.000000  ...    1.000000   

         monthfeb    monthjan    monthjul    monthjun    monthmar    monthmay  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean     0.038685    0.003868    0.061896    0.032882    0.104449    0.003868   
std      0.193029    0.062137    0.241199    0.178500    0.306138    0.062137   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
75%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

         monthnov    monthoct    monthsep  
count  517.000000  517.000000  517.000000  
mean     0.001934    0.029014    0.332689  
std      0.043980    0.168007    0.471632  
min      0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000  
75%      0.000000    0.000000    1.000000  
max      1.000000    1.000000    1.000000  

[8 rows x 28 columns]

In [6]:
forestfire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   month          517 non-null    object 
 1   day            517 non-null    object 
 2   FFMC           517 non-null    float64
 3   DMC            517 non-null    float64
 4   DC             517 non-null    float64
 5   ISI            517 non-null    float64
 6   temp           517 non-null    float64
 7   RH             517 non-null    int64  
 8   wind           517 non-null    float64
 9   rain           517 non-null    float64
 10  area           517 non-null    float64
 11  dayfri         517 non-null    int64  
 12  daymon         517 non-null    int64  
 13  daysat         517 non-null    int64  
 14  daysun         517 non-null    int64  
 15  daythu         517 non-null    int64  
 16  daytue         517 non-null    int64  
 17  daywed         517 non-null    int64  
 18  monthapr  

In [7]:
## dropping object datatype

forestfire.drop(["month","day"],axis=1,inplace = True)

In [8]:
forestfire

FFMC    DMC     DC   ISI  temp  RH  wind  rain   area  dayfri  ...  \
0    86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00       1  ...   
1    90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00       0  ...   
2    90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00       0  ...   
3    91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00       1  ...   
4    89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00       0  ...   
..    ...    ...    ...   ...   ...  ..   ...   ...    ...     ...  ...   
512  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44       0  ...   
513  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29       0  ...   
514  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16       0  ...   
515  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00       0  ...   
516  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00       0  ...   

     monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  \
0           0         0         0         0         1         0         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         1         0         0   
4           0         0         0         0         1         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         1   

     monthoct  monthsep  size_category  
0           0         0          small  
1           1         0          small  
2           1         0          small  
3           0         0          small  
4           0         0          small  
..        ...       ...            ...  
512         0         0          large  
513         0         0          large  
514         0         0          large  
515         0         0          small  
516         0         0          small  

[517 rows x 29 columns]

In [13]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
forestfire["size_category"] = lb.fit_transform(forestfire["size_category"])
forestfire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 29 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   FFMC           517 non-null    float64
 1   DMC            517 non-null    float64
 2   DC             517 non-null    float64
 3   ISI            517 non-null    float64
 4   temp           517 non-null    float64
 5   RH             517 non-null    int64  
 6   wind           517 non-null    float64
 7   rain           517 non-null    float64
 8   area           517 non-null    float64
 9   dayfri         517 non-null    int64  
 10  daymon         517 non-null    int64  
 11  daysat         517 non-null    int64  
 12  daysun         517 non-null    int64  
 13  daythu         517 non-null    int64  
 14  daytue         517 non-null    int64  
 15  daywed         517 non-null    int64  
 16  monthapr       517 non-null    int64  
 17  monthaug       517 non-null    int64  
 18  monthdec  

In [14]:
forestfire["size_category"].value_counts()

1    378
0    139
Name: size_category, dtype: int64

There are 378 small fires & 139 large fires

In [15]:
forestfire.isnull().sum()

FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

There are no null values in the dataframe

In [35]:
forestfire.loc[forestfire["size_category"]=='small','size_category']=0
forestfire.loc[forestfire["size_category"]=='large','size_category']=1
forestfire["size_category"].value_counts()

1    378
0    139
Name: size_category, dtype: int64

In [16]:
## Normalization function

def norm_func(i):
     x = (i-i.min())/(i.max()-i.min())
     return (x)

In [17]:
predictors = forestfire.iloc[:,0:28]
target = forestfire.iloc[:,28]

In [18]:
target

0      1
1      1
2      1
3      1
4      1
      ..
512    0
513    0
514    0
515    1
516    1
Name: size_category, Length: 517, dtype: int64

In [19]:
predictors1 = norm_func(predictors)
firedata = pd.concat([predictors1,target],axis=1)

In [20]:
firedata

FFMC       DMC        DC       ISI      temp        RH      wind  \
0    0.870968  0.086492  0.101325  0.090909  0.192926  0.423529  0.700000   
1    0.927742  0.118194  0.775419  0.119430  0.508039  0.211765  0.055556   
2    0.927742  0.146795  0.796294  0.119430  0.398714  0.211765  0.100000   
3    0.941935  0.110958  0.081623  0.160428  0.196141  0.964706  0.400000   
4    0.910968  0.172984  0.110590  0.171123  0.295820  0.988235  0.155556   
..        ...       ...       ...       ...       ...       ...       ...   
512  0.811613  0.191592  0.771315  0.033868  0.823151  0.200000  0.255556   
513  0.811613  0.191592  0.771315  0.033868  0.633441  0.658824  0.600000   
514  0.811613  0.191592  0.771315  0.033868  0.610932  0.647059  0.700000   
515  0.976774  0.499311  0.711622  0.201426  0.752412  0.317647  0.400000   
516  0.784516  0.006547  0.115867  0.019608  0.308682  0.188235  0.455556   

        rain      area  dayfri  ...  monthfeb  monthjan  monthjul  monthjun  \
0    0.00000  0.000000     1.0  ...       0.0       0.0       0.0       0.0   
1    0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   
2    0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   
3    0.03125  0.000000     1.0  ...       0.0       0.0       0.0       0.0   
4    0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   
..       ...       ...     ...  ...       ...       ...       ...       ...   
512  0.00000  0.005904     0.0  ...       0.0       0.0       0.0       0.0   
513  0.00000  0.049769     0.0  ...       0.0       0.0       0.0       0.0   
514  0.00000  0.010231     0.0  ...       0.0       0.0       0.0       0.0   
515  0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   
516  0.00000  0.000000     0.0  ...       0.0       0.0       0.0       0.0   

     monthmar  monthmay  monthnov  monthoct  monthsep  size_category  
0         1.0       0.0       0.0       0.0       0.0              1  
1         0.0       0.0       0.0       1.0       0.0              1  
2         0.0       0.0       0.0       1.0       0.0              1  
3         1.0       0.0       0.0       0.0       0.0              1  
4         1.0       0.0       0.0       0.0       0.0              1  
..        ...       ...       ...       ...       ...            ...  
512       0.0       0.0       0.0       0.0       0.0              0  
513       0.0       0.0       0.0       0.0       0.0              0  
514       0.0       0.0       0.0       0.0       0.0              0  
515       0.0       0.0       0.0       0.0       0.0              1  
516       0.0       0.0       1.0       0.0       0.0              1  

[517 rows x 29 columns]

In [21]:
## splitting the data into train & test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(predictors1,target, test_size=0.3,stratify = target)

In [26]:
def prep_model(hidden_dim):
    model=Sequential()
    for i in range(1,len(hidden_dim)-1):
        if (i==1):
            model.add(Dense(hidden_dim[i],input_dim=hidden_dim[0],activation="relu"))
        else:
            model.add(Dense(hidden_dim[i],activation="relu"))
    model.add(Dense(hidden_dim[-1],kernel_initializer="normal",activation="sigmoid"))
    model.compile(loss="binary_crossentropy",optimizer = "rmsprop",metrics = ["accuracy"])
    return model

In [27]:
y_train

446    1
385    0
417    1
506    1
350    1
      ..
480    1
380    0
492    1
9      1
301    1
Name: size_category, Length: 361, dtype: int64

In [72]:
first_model = prep_model([28,50,40,20,1])
first_model.fit(np.array(x_train),np.array(y_train),epochs=500)
pred_train = first_model.predict(np.array(x_train))

Epoch 1/500
12/12 [==============================] - 1s 3ms/step - loss: 0.6810 - accuracy: 0.6925
Epoch 2/500
12/12 [==============================] - 0s 2ms/step - loss: 0.6424 - accuracy: 0.7313
Epoch 3/500
12/12 [==============================] - 0s 2ms/step - loss: 0.6061 - accuracy: 0.7313
Epoch 4/500
12/12 [==============================] - 0s 2ms/step - loss: 0.5899 - accuracy: 0.7313
Epoch 5/500
12/12 [==============================] - 0s 2ms/step - loss: 0.5849 - accuracy: 0.7313
Epoch 6/500
12/12 [==============================] - 0s 2ms/step - loss: 0.5800 - accuracy: 0.7313
Epoch 7/500
12/12 [==============================] - 0s 2ms/step - loss: 0.5789 - accuracy: 0.7313
Epoch 8/500
12/12 [==============================] - 0s 2ms/step - loss: 0.5769 - accuracy: 0.7313
Epoch 9/500
12/12 [==============================] - 0s 2ms/step - loss: 0.5743 - accuracy: 0.7313
Epoch 10/500
12/12 [==============================] - 0s 2ms/step - loss: 0.5729 - accuracy: 0.7313
Epoch 11/

12/12 [==============================] - 0s 2ms/step - loss: 0.1237 - accuracy: 0.9446
Epoch 164/500
12/12 [==============================] - 0s 2ms/step - loss: 0.1224 - accuracy: 0.9557
Epoch 165/500
12/12 [==============================] - 0s 3ms/step - loss: 0.1271 - accuracy: 0.9474
Epoch 166/500
12/12 [==============================] - 0s 3ms/step - loss: 0.1172 - accuracy: 0.9446
Epoch 167/500
12/12 [==============================] - 0s 3ms/step - loss: 0.1240 - accuracy: 0.9474
Epoch 168/500
12/12 [==============================] - 0s 3ms/step - loss: 0.1145 - accuracy: 0.9640
Epoch 169/500
12/12 [==============================] - 0s 1ms/step - loss: 0.1191 - accuracy: 0.9557
Epoch 170/500
12/12 [==============================] - 0s 2ms/step - loss: 0.1172 - accuracy: 0.9501
Epoch 171/500
12/12 [==============================] - 0s 2ms/step - loss: 0.1117 - accuracy: 0.9529
Epoch 172/500
12/12 [==============================] - 0s 2ms/step - loss: 0.1119 - accuracy: 0.9612
Epoc

12/12 [==============================] - 0s 3ms/step - loss: 0.0131 - accuracy: 1.0000
Epoch 325/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0142 - accuracy: 1.0000
Epoch 326/500
12/12 [==============================] - 0s 3ms/step - loss: 0.0583 - accuracy: 0.9751
Epoch 327/500
12/12 [==============================] - 0s 3ms/step - loss: 0.0066 - accuracy: 1.0000
Epoch 328/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0061 - accuracy: 1.0000
Epoch 329/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0192 - accuracy: 0.9917
Epoch 330/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0091 - accuracy: 1.0000
Epoch 331/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0412 - accuracy: 0.9834
Epoch 332/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0119 - accuracy: 0.9972
Epoch 333/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0137 - accuracy: 0.9972
Epoc

12/12 [==============================] - 0s 2ms/step - loss: 0.0099 - accuracy: 0.9972
Epoch 487/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0181 - accuracy: 0.9889
Epoch 488/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0025 - accuracy: 1.0000
Epoch 489/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0015 - accuracy: 1.0000
Epoch 490/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0337 - accuracy: 0.9834
Epoch 491/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 492/500
12/12 [==============================] - 0s 2ms/step - loss: 9.1619e-04 - accuracy: 1.0000
Epoch 493/500
12/12 [==============================] - 0s 2ms/step - loss: 6.5907e-04 - accuracy: 1.0000
Epoch 494/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0109 - accuracy: 0.9945
Epoch 495/500
12/12 [==============================] - 0s 2ms/step - loss: 0.0242 - accuracy: 0.9

In [36]:
#Converting the predicted values to series 
pred_train = pd.Series([i[0] for i in pred_train])

In [37]:
size = ["small","large"]
pred_train_class = pd.Series(["small"]*361)
pred_train_class[[i>0.5 for i in pred_train]]= "large"

In [38]:
train = pd.concat([x_train,y_train],axis=1)
train["size_category"].value_counts()

1    264
0     97
Name: size_category, dtype: int64

In [39]:
#For training data
from sklearn.metrics import confusion_matrix
train["original_class"] = "small"
train.loc[train["size_category"]==1,"original_class"] = "large"
train.original_class.value_counts()

large    264
small     97
Name: original_class, dtype: int64

In [41]:
confusion_matrix(pred_train_class,train["original_class"])

array([[264,   0],
       [  0,  97]], dtype=int64)

In [43]:
np.mean(pred_train_class==pd.Series(train["original_class"]).reset_index(drop=True)) #100%

1.0

Train data is 100% accuracy

In [44]:
pd.crosstab(pred_train_class,pd.Series(train["original_class"]).reset_index(drop=True))

original_class  large  small
row_0                       
large             264      0
small               0     97

In [46]:
#For test data
pred_test = first_model.predict(np.array(x_test))
pred_test = pd.Series([i[0] for i in pred_test])
pred_test

0      1.000000e+00
1      1.000000e+00
2      1.000000e+00
3      1.194912e-02
4      2.756410e-19
           ...     
151    1.151526e-12
152    9.999743e-01
153    9.971818e-01
154    4.288249e-09
155    1.000000e+00
Length: 156, dtype: float64

In [48]:
pred_test_class = pd.Series(["small"]*156)
pred_test_class[[i>0.5 for i in pred_test]] = "large"

In [49]:
test =pd.concat([x_test,y_test],axis=1)
test["original_class"]="small"
test.loc[test["size_category"]==1,"original_class"] = "large"

In [50]:
test["original_class"].value_counts()

large    114
small     42
Name: original_class, dtype: int64

In [51]:
np.mean(pred_test_class==pd.Series(test["original_class"]).reset_index(drop=True)) # 85%

0.8461538461538461

Test data has 84.6% accuracy

In [52]:
confusion_matrix(pred_test_class,test["original_class"])

array([[100,  10],
       [ 14,  32]], dtype=int64)

In [70]:
pd.crosstab(pred_test_class,pd.Series(test["original_class"]).reset_index(drop=True))

original_class  large  small
row_0                       
large             100     10
small              14     32

# Visualizing ANN

In [ ]:
ann_viz(first_model, view=True, filename="forestfire.gv", title="ForestFireANN")

In [ ]:
from ann_visualizer.visualize import ann_viz;

ann_viz(model, title="ForestFireANN")